from pydantic import AnyUrl, BaseModel, Field, FilePath, ConfigDict, HttpUrl
from typing import Optional, Literal, List

# ─── BASE SCHEMAS ───────────────────────────────────────────────────────────────
# These are the core blueprints for our data. They are used for creation,
# so we don't include fields that are generated by the database, like `id`
# or `created_at`.

# ─── CATEGORY SCHEMAS ───────────────────────────────────────────────────────────
class CategoryBase(BaseModel):
    """Base schema for a category, defining the core fields."""
    name: str = Field(..., min_length=3)
    model_config = ConfigDict(str_strip_whitespace=True)

class CategoryCreate(CategoryBase):
    """Schema for creating a new category."""
    pass

class CategoryResponse(CategoryBase):
    """Schema for representing a category in API responses."""
    id: int
    model_config = ConfigDict(from_attributes=True)

class CategoryUpdate(BaseModel):
    """Schema for updating an existing category."""
    id: int
    name: Optional[str] = Field(None, min_length=3)
    model_config = ConfigDict(str_strip_whitespace=True)

# ─── MASTER PDF SCHEMAS ─────────────────────────────────────────────────────────
class MasterPDFBase(BaseModel):
    """Base schema for a master PDF document."""
    name: str = Field(..., min_length=3)
    file_path: FilePath
    model_config = ConfigDict(str_strip_whitespace=True)

class MasterPDFCreate(MasterPDFBase):
    """Schema for creating a new master PDF.

    Accepts either the name or the ID of the parent category.
    """
    category_value: str | int = Field(..., description="The ID or name of the parent category.")

class MasterPDFResponse(MasterPDFBase):
    """Schema for representing a master PDF document in API responses."""
    id: int
    category_id: int
    model_config = ConfigDict(from_attributes=True)

class MasterPDFUpdate(BaseModel):
    """Schema for updating an existing master PDF."""
    id: int
    name: Optional[str] = Field(None, min_length=3)
    file_path: Optional[FilePath] = None
    category_value: Optional[str | int] = Field(None, description="The ID or name of the parent category.")
    model_config = ConfigDict(str_strip_whitespace=True)

# ─── PDF SCHEMAS ────────────────────────────────────────────────────────────────
class PDFBase(BaseModel):
    """Base schema for an individual PDF link."""
    url: str = Field(..., min_length=3)
    file_path: Optional[FilePath] = None
    status: Literal["PEND", "FAIL", "SUCC"] = "PEND"
    master_page_number: Optional[int] = Field(default=None, description="The page # which this PDF begins on in the parent masterPDF, if specified will attempt to insert pdf within master on specified page.")
    video_links: Optional[List[str]] = Field(default_factory=list, description="A list of video URLs associated with the PDF.")

class PDFCreate(PDFBase):
    """Schema for creating a new PDF link.

    Associates the PDF with a parent MasterPDF by its name or ID.
    """
    master_pdf_value: Optional[str | int] = Field(..., description="The ID or name of the parent masterPDF.")

class PDFResponse(PDFBase):
    """Schema for representing an individual PDF link in API responses."""
    id: int
    master_id: int
    url: str
    model_config = ConfigDict(from_attributes=True)

class PDFUpdate(BaseModel):
    """Schema for updating an existing PDF link."""
    id: int
    url: Optional[str] = Field(None, min_length=3)
    file_path: Optional[FilePath] = None
    status: Optional[Literal["PEND", "FAIL", "SUCC"]] = None
    master_page_number: Optional[int] = None
    video_links: Optional[List[str]] = None
    master_pdf_value: Optional[str | int] = Field(None, description="The ID or name of the parent masterPDF.")

# ─── UNPROCESSED PDF SCHEMAS ────────────────────────────────────────────────────
class UnprocessedPDFBase(BaseModel):
    """Base schema for an unprocessed PDF (only has category, no master PDF yet)."""
    url: str = Field(..., min_length=3)
    file_path: Optional[str] = None
    video_links: Optional[List[str]] = Field(default_factory=list)

class UnprocessedPDFCreate(UnprocessedPDFBase):
    """Schema for creating a new unprocessed PDF."""
    category_value: str | int = Field(..., description="The ID or name of the parent category.")

class UnprocessedPDFResponse(UnprocessedPDFBase):
    """Schema for representing an unprocessed PDF in API responses."""
    id: int
    category_id: int
    model_config = ConfigDict(from_attributes=True)

class UnprocessedPDFUpdate(BaseModel):
    """Schema for updating an existing unprocessed PDF."""
    id: int
    url: Optional[str] = Field(None, min_length=3)
    file_path: Optional[str] = None
    video_links: Optional[List[str]] = None
    category_value: Optional[str | int] = Field(None, description="The ID or name of the parent category.")
